CREATE TABLE MEMBER(
	MPK INT AUTO_INCREMENT PRIMARY KEY,
	MID VARCHAR(10) UNIQUE,
	MPW VARCHAR(10) NOT NULL,
	MNAME VARCHAR(20) NOT NULL
);
drop table member;

insert into member values('tt','q','tt');
insert into member values('q','q','tt');
insert into member values('e','q','tt');
insert into member values('f','q','tt');
insert into member values('Z','q','tt');
insert into member values('a','q','tt');

SELECT * FROM MEMBER;

SELECT * FROM (SELECT A. ,ROWNUM AS RNUM FROM (SELECT FROM MEMBER ORDER BY ROWNUM DESC) A WHERE ROWNUM<=3) WHERE RNUM>=1;
CREATE TABLE BOARD(
	BID INT PRIMARY KEY AUTO_INCREMENT,
	MID VARCHAR(10) NOT NULL, -- FK는 반드시 상대 테이블의 PK를 사용
	MSG VARCHAR(50) NOT NULL,
	FAVCNT INT DEFAULT 0,
	RCNT INT DEFAULT 0
);
CREATE TABLE REPLY(
	RID INT PRIMARY KEY AUTO_INCREMENT,
	MID VARCHAR(10) NOT NULL,
	BID INT NOT NULL,
	RMSG VARCHAR(30) NOT NULL,
	CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD (BID) ON DELETE CASCADE
);


SELECT @ROWNUM:=@ROWNUM+1 AS RNUM, A.* FROM MEMBER A, (SELECT @ROWNUM:=0) R;